apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: go-api
spec:
  replicas: 10
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: tayyab7891/sportsapiv1:v12
        ports:
        - containerPort: 5001
