apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app.kubernetes.io/name: go-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

