apiVersion: v1
kind: Service
metadata:
  name: go-service
  labels:
    app: go-api
spec:
  type: LoadBalancer
  selector:
    app: go-api
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5001
